spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: js@2020
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.50.107:33306/spring-boot-demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
        slave:
          username: root
          password: js@2020
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.50.107:33306/spring-boot-demo-2?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
      mp-enabled: true

logging:
  level:
    com.kxuer: debug

